#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
runcase mesh-20 "(60 20 1)" "post" "komegasst"
runcase mesh-40 "(120 40 1)" "post" "komegasst"
runcase mesh-60 "(180 60 1)" "post" "komegasst"
runcase mesh-80 "(240 80 1)" "post" "komegasst"
runcase mesh-120 "(360 120 1)" "post" "komegasst"
runcase mesh-160 "(480 160 1)" "post" "komegasst"

analysis

pressuredrop

#############################################























