#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
#runcase mesh-20 "(60 20 1)" "clean mesh run post" "komegasst"
runcase mesh-20 "(60 20 1)" "clean mesh run post" "komegasst"

#############################################























