#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
runcase mesh-pimple-160-fine "(480 160 1)" "clean mesh run post" "komegasst"
#runcase mesh-pimple-160-fine "(480 160 1)" "post" "komegasst"

#############################################























