#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory












#############################################
source ./runcase
#############################################

# folder     cellsnumber     nOuterCorrectors     nCorrectors    maxCo    command    options
runcase pimple-60 "(180 60 1)" 1 20 50 "clean mesh run post" "komegasst"

#############################################























