#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory












#############################################
source ./runcase
#############################################

# folder     cellsnumber     nOuterCorrectors     nCorrectors    maxCo    command    options
runcase pimple120-20-1-20 "(360 120 1)" 20 1 20 "clean mesh run post" "komegasst"

#############################################























