#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory












#############################################
source ./runcase
#############################################

# folder     cellsnumber     nOuterCorrectors     nCorrectors    maxCo    command    options
runcase piso-60 "(180 60 1)" 2 1 0.75 "clean mesh run post" "komegasst"

#############################################























