#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory












#############################################
source ./runcase
#############################################

# folder     cellsnumber     nOuterCorrectors     nCorrectors    maxCo    command    options
runcase pimple120 "(360 120 1)" 100 3 1000 "run post" "komegasst"

#############################################























