#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
# runcase mesh-120-nonort "(360 120 1)" "clean mesh run post" "komegasst" 1 5 30 3 2.4 1 8
runcase mesh-120-nonort2 "(360 120 1)" "clean mesh run post" "komegasst" 1 3 30 3 2.4 1 10

#############################################























