#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
#runcase mesh-pimple-120 "(360 120 1)" "clean mesh run post" "komegasst"
runcase mesh-240 "(720 240 1)" "clean mesh run post" "komegasst"

#############################################























