#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
runcase mesh-pimple60 "(180 60 1)" "clean mesh run post" "komegasst"
#runcase mesh-pimple-120 "(360 120 1)" "post" "komegasst"

#############################################























