#!/bin/bash
function runcase() # folder     cellsnumber     nOuterCorrectors     nCorrectors    maxCo    command    options
{   
    #set -x
    folder="$1"
    cells="$2"
    nOuterCorrectors=1
    nCorrectors=20
    maxCo=50
    endTime=2.4
    
    if [ ! -n "$3" ]
    then
        command="clean mesh run post"
    else 
        command="$3"
    fi
    
    echo "Running case "
    
    if [ ! -d $folder ]; then
        mkdir $folder
        mkdir $folder/main
        cp ../mesh/* $folder -r
        cp ../main $folder/ -r
    fi
    
    # change parameters according to user options
    echo $cells > $folder/include/cells-array
    echo $nOuterCorrectors > $folder/main/controls/nOuterCorrectors
    echo $nCorrectors > $folder/main/controls/nCorrectors
    echo $maxCo > $folder/main/controls/maxCo
    echo $endTime > $folder/main/controls/endTime
    
    if [ ! -n "$4" ]; then
        ../Myrun "$command" "map-fields/$folder" "map-fields/$folder"
    else
        ../Myrun "$command" "map-fields/$folder" "map-fields/$folder" "$4" # options parameter
    fi
}


function analysis()
{
	#     cells:            9696
	cells20=$(checkMesh -case mesh-pimple-20/main/ -latestTime | grep cells | head -n 1)
	cells40=$(checkMesh -case mesh-pimple-40/main/ -latestTime | grep cells | head -n 1)
	cells60=$(checkMesh -case mesh-pimple-60/main/ -latestTime | grep cells | head -n 1)
	cells80=$(checkMesh -case mesh-pimple-80/main/ -latestTime | grep cells | head -n 1)
	cells120=$(checkMesh -case mesh-pimple-120/main/ -latestTime | grep cells | head -n 1)
	cells160=$(checkMesh -case mesh-pimple-160/main/ -latestTime | grep cells | head -n 1)
	cells200=$(checkMesh -case mesh-pimple-200/main/ -latestTime | grep cells | head -n 1)
	
	# -4.70985928088# mean power [W]
	power20=$(cat mesh-pimple-20/main/fig/meanpower)
	power40=$(cat mesh-pimple-40/main/fig/meanpower)
	power60=$(cat mesh-pimple-60/main/fig/meanpower)
	power80=$(cat mesh-pimple-80/main/fig/meanpower)
	power120=$(cat mesh-pimple-120/main/fig/meanpower)
	power160=$(cat mesh-pimple-160/main/fig/meanpower)
	power200=$(cat mesh-pimple-200/main/fig/meanpower)
	
	echo $cells20 > power
	echo $cells40 >> power
	echo $cells60 >> power
	echo $cells80 >> power
	echo $cells120 >> power
	echo $cells160 >> power
	echo $cells200 >> power
	
	echo $power20 >> power
	echo $power40 >> power
	echo $power60 >> power
	echo $power80 >> power
	echo $power120 >> power
	echo $power160 >> power
	echo $power200 >> power
}

