#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Arguments:
#if [ ! -n "$1" ]
#then
#    deg0=0
#    echo "Reference angle = 0"
#else
#    deg0=$1
#fi

#name="blade0"
# get the name of the current directory
name=${PWD##*/}  

#echo "--------------------------------"
echo "Running blockMesh for $name..."
start_time="$(date -u +%s.%N)"
blockMesh > log/log.blockMesh

echo "Running snappyHexMesh for $name..."
snappyHexMesh -overwrite > log/log.snappyHexMesh
end_time="$(date -u +%s.%N)"
elapsed="$(bc <<<"$end_time-$start_time")"
echo "$name Duration = $elapsed seconds"

# setSet commands

#setSet -batch setSetDict

#faceSet AMI-int0-faceSet new patchToFace AMI-int0
#faceZoneSet AMI-int0-faceZoneSet new setToFaceZone AMI-int0-faceSet

#################
# ----------------------------------------------------------------- end-of-file
