#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# - meshing

runApplication blockMesh

runApplication surfaceFeatureExtract

runApplication snappyHexMesh -overwrite

runApplication createBaffles -overwrite

runApplication mergeOrSplitBaffles -split -overwrite 

runApplication createPatch -overwrite

runApplication renumberMesh -overwrite



