#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################
source ./runcase
#############################################

#           folder     cellsnumber      command             options
#runcase mesh-pimple-120 "(360 120 1)" "clean mesh run post" "komegasst"
# folder     cellsnumber   command    options  nOuterCorrectors     nCorrectors    maxCo   refineWallLayerNumber     endTime         initialU

meshcells="(240 80 1)"

# mesh only
###
# runcase mesh-only "$meshcells" "clean mesh" "komegasst" 1 13 30 3 2.4 5.75958653158129
# 
# cp -r mesh-only bsr-0.1
# cp -r mesh-only bsr-0.25
# cp -r mesh-only bsr-0.5
# cp -r mesh-only bsr-0.75
# cp -r mesh-only bsr-0.9
###

runcase bsr-0.1 "$meshcells" "run post resume" "komegasst" 1 13 75 3 2.4 5.75958653158129

runcase bsr-0.25 "$meshcells" "run post" "komegasst" 1 13 60 3 2.4 2.30383461263251

runcase bsr-0.5 "$meshcells" "run post" "komegasst" 1 13 35 3 2.4 1.15191730631626

runcase bsr-0.75 "$meshcells" "run post" "komegasst" 1 13 25 3 2.4 0.767944870877505

runcase bsr-0.9 "$meshcells" "run post" "komegasst" 1 13 20 3 2.4 0.639954059064587


#############################################























