#!/bin/bash
function runcase() # folder     cellsnumber     nOuterCorrectors     nCorrectors    maxCo    command    options
{   
    #set -x
    folder="$1"
    cells="$2"
    nOuterCorrectors=1
    nCorrectors=20
    maxCo=50
    endTime=2.4
    
    if [ ! -n "$3" ]
    then
        command="clean mesh run post"
    else 
        command="$3"
    fi
    
    echo "Running case "
    
    if [ ! -d $folder ]; then
        mkdir $folder
        mkdir $folder/main
        cp ../mesh/* $folder -r
        cp ../main $folder/ -r
    fi
    
    # change parameters according to user options
    echo $cells > $folder/include/cells-array
    echo $nOuterCorrectors > $folder/main/controls/nOuterCorrectors
    echo $nCorrectors > $folder/main/controls/nCorrectors
    echo $maxCo > $folder/main/controls/maxCo
    echo $endTime > $folder/main/controls/endTime
    
    
    # get the name of the current directory
    name=${PWD##*/}  
    
    if [ ! -n "$4" ]; then
        ../Myrun "$command" "$name/$folder" "$name/$folder"
    else
        ../Myrun "$command" "$name/$folder" "$name/$folder" "$4" # options parameter
    fi
}

function pressuredrop()
{
    allsimulations=( "mesh-40" )
    
    echo "inlet         oulet" >> totalpressure
    
    for i in "${allsimulations[@]}"
    do
        echo $i 
        postProcess -func 'totalPressureIncompressible(U,p)' -case $i/main -time '0'
        postProcess -func 'totalPressureIncompressible(U,p)' -case $i/main -latestTime
        postProcess -func 'patchAverage(name=inlet,total(p))' -case $i/main -latestTime #-time '0'
        postProcess -func 'patchAverage(name=outlet,total(p))' -case $i/main -latestTime
        inlet=$(cat $i/main/postProcessing/patchAverage\(name\=inlet\,total\(p\)\)/0/surfaceFieldValue.dat | tail -n 1 | awk -F" " '{print $NF}')
        outlet=$(cat $i/main/postProcessing/patchAverage\(name\=outlet\,total\(p\)\)/0/surfaceFieldValue.dat | tail -n 1 | awk -F" " '{print $NF}')
        echo "$inlet       $outlet     || $i "  >> totalpressure
    done
    
}


function analysis()
{
    allsimulations=("mesh-40")
    
    #echo "" > power
    # print cell numbers
    for i in "${allsimulations[@]}"
    do
        cells=$(checkMesh -case $i/main/ -latestTime | grep cells | head -n 1)
        echo $cells >> power
    done
    
    # print power
    echo "######### POWER TOTAL ####################" >> power
    for i in "${allsimulations[@]}"
    do
        power=$(cat $i/main/fig/meanpower | head -n 1)
        echo $power >> power
    done
    
    echo "######### POWER PRESSURE #################" >> power
    for i in "${allsimulations[@]}"
    do
        power=$(cat $i/main/fig/meanpowerpressure | head -n 1)
        echo $power >> power
    done
    
    echo "######### POWER TAU ######################" >> power
    for i in "${allsimulations[@]}"
    do
        power=$(cat $i/main/fig/meanpowertau | head -n 1)
        echo $power >> power
    done
    echo "##########################################" >> power
    
    # print nut
    for i in "${allsimulations[@]}"
    do
        nut=$(cat $i/main/fig/meannut | head -n 1)
        echo $nut >> power
    done
    cat power
}

