#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory


#############################################

function runcase() 
{   
    #set -x
    folder="$1"
    cells="$2"
    
    if [ ! -n "$3" ]
    then
        command="clean mesh run post"
    else 
        command="$3"
    fi
    
    echo "Running case "
    
    if [ ! -d $folder ]; then
        mkdir $folder
        mkdir $folder/main
        cp ../mesh/* $folder -r
        cp ../main $folder/ -r
    fi
    
    echo $cells > $folder/include/cells-array
    
    if [ ! -n "$4" ]; then
        ../Myrun "$command" "mesh-sensitivity/$folder" "mesh-sensitivity/$folder"
    else
        ../Myrun "$command" "mesh-sensitivity/$folder" "mesh-sensitivity/$folder" "$4" # options parameter
    fi
    
    #    ../Myrun "clean mesh run post" "mesh-sensitivity/$folder" "mesh-sensitivity/$folder"
}

#############################################

#runcase mesh-10-komegasst "(30 10 1)" "clean mesh run post" "komegasst"
#runcase mesh-10-kepsilon "(30 10 1)" "clean mesh run post" "kepsilon"

#runcase mesh-20 "(60 20 1)" &
#runcase mesh-120 "(360 120 1)" &
#wait
#runcase mesh-40 "(120 40 1)" &
#runcase mesh-80 "(240 80 1)"

#runcase mesh-60-kw "(180 60 1)" "clean mesh run post" "komegasst"
runcase mesh-60-test "(180 60 1)" "run post" "komegasst"

#mapFields -case mesh-120-par/main/ mesh-80/main/ -consistent
#runcase mesh-120 "(360 120 1)"
#wait
#runcase mesh-115 "(345 115 1)"

#############################################

