#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# if [ ! -f CAD-scaled/blade0.stl ]; then
#     echo "Scaling of file blade0..."
#     surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/blade0.stl  CAD-scaled/blade0.stl
# fi
 
mkdir CAD-scaled > /dev/null 2>&1

echo "Scaling stl files..."
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/blade0.stl  CAD-scaled/blade0.stl > /dev/null 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/blade1.stl  CAD-scaled/blade1.stl > /dev/null 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/blade2.stl  CAD-scaled/blade2.stl > /dev/null 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/AMI-int0.stl  CAD-scaled/AMI-int0.stl > /dev/null 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/AMI-int1.stl  CAD-scaled/AMI-int1.stl > /dev/null 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/AMI-int2.stl  CAD-scaled/AMI-int2.stl > /dev/null 2>&1
surfaceTransformPoints -scale '(0.001 0.001 0.001)' CAD/AMI-ext.stl  CAD-scaled/AMI-ext.stl > /dev/null 2>&1

    
echo "Copying stl files into folders..."
cp CAD-scaled/blade0.stl blade0/constant/triSurface/blade0.stl
cp CAD-scaled/blade1.stl blade1/constant/triSurface/blade1.stl
cp CAD-scaled/blade2.stl blade2/constant/triSurface/blade2.stl

cp CAD-scaled/AMI-int0.stl blade0/constant/triSurface/AMI-int0.stl
cp CAD-scaled/AMI-int0.stl circle-ext/constant/triSurface/AMI-int0.stl

cp CAD-scaled/AMI-int1.stl blade1/constant/triSurface/AMI-int1.stl
cp CAD-scaled/AMI-int1.stl circle-ext/constant/triSurface/AMI-int1.stl

cp CAD-scaled/AMI-int2.stl blade2/constant/triSurface/AMI-int2.stl
cp CAD-scaled/AMI-int2.stl circle-ext/constant/triSurface/AMI-int2.stl

cp CAD-scaled/AMI-ext.stl steady/constant/triSurface/AMI-ext.stl
cp CAD-scaled/AMI-ext.stl circle-ext/constant/triSurface/AMI-ext.stl

