#!/bin/bash
#cd ${0%/*} || exit 1    # run from this directory

#############################################
source ./runcase
#############################################

# echo $command
# echo $options
# echo $nOuterCorrectors
# echo $nCorrectors
# echo $maxCo
# echo $refineWallLayerNumber
# echo $endTime
# echo $initialU
# echo $nNonOrthogonalCorrectors
#runcase final2 "(540 120 1)" "clean mesh run post" "komegasst" 1 20 20 3 3.6 1 0
runcase final4 "(540 120 1)" "run post" "komegasst" 1 3 5 3 3.6 1 2

#############################################
